#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/docker-options/functions"

get_permitted_port() {
  declare desc="returns first currently unused port > 1024"
  while true; do
    local port=$(shuf -i 8010-12000 -n 1)
    if ! nc -z 0.0.0.0 "$port"; then
      echo "$port"
      return 0
    else
      continue
    fi
  done
}

haproxy_configure_container_port_mappings() {
  declare desc="return port pairs"
  local trigger="docker-args-process-deploy"
  local APP="$1" PROC_TYPE="$2" CONTAINER_INDEX="$3"

  # 1. Get all exposed ports in the web proc type
  # 2. For each exposed port, get a raw port
  # 3. For each pair (raw port, exposed), generate a -p <raw>:<exposed>/tcp to add to the port map
  # 4. Set the port map
  local HAPROXY_CONFIG_PATH="$DOKKU_ROOT/$APP/HAPROXY_RUNTIME_CONFIG"
  if [[ "$CONTAINER_INDEX" == "1" ]] ; then
      echo "# HAPROXY Runtime Configuration" > "$HAPROXY_CONFIG_PATH"
  fi

  local LOCAL_IP="$(hostname --ip-address)"
  
  local NEW_PROXY_PORT_MAP
  if [[ "web" == "$PROC_TYPE" ]] ; then
      local RAW_TCP_PORTS="$(get_app_raw_tcp_ports "$APP")"

      local DOKKU_APP_LISTENERS="$(plugn trigger network-get-listeners "$APP" "$PROC_TYPE" | xargs)"
      
      # wipe it
      dokku_log_warn "LISTENERS: $DOKKU_APP_LISTENERS"
      dokku_log_warn "RAW PORTS: $RAW_TCP_PORTS"
      
      if [[ -n "$RAW_TCP_PORTS" ]]; then
          local RAW_TCP_PORT
          for RAW_TCP_PORT in $RAW_TCP_PORTS; do
              local AVAILABLE_TCP_PORT=$(get_permitted_port)
              NEW_PROXY_PORT_MAP+="-p $AVAILABLE_TCP_PORT:$RAW_TCP_PORT/tcp "

              # Update the HAPROXY_CONFIG_PATH
              echo "set server ${APP}-backend/${APP}-server-${CONTAINER_INDEX} addr ${LOCAL_IP} port ${AVAILABLE_TCP_PORT}" >> "$HAPROXY_CONFIG_PATH"
              echo "set server ${APP}-backend/${APP}-server-${CONTAINER_INDEX} state ready" >> "$HAPROXY_CONFIG_PATH"
                            
              dokku_log_warn "Container #${CONTAINER_INDEX}: linking $AVAILABLE_TCP_PORT to $RAW_TCP_PORT"
              DOKKU_QUIET_OUTPUT=1 config_set --no-restart "$APP" "DOKKU_WEB_CONTAINER_PORT_$CONTAINER_INDEX"="$AVAILABLE_TCP_PORT"
          done          
      fi
  fi
  echo $NEW_PROXY_PORT_MAP
}

haproxy_configure_container_ipaddr() {
  declare desc="configure container IP address"
  local trigger="network-write-ipaddr"
  local APP="$1"
}

haproxy_retrieve_container_port() {
  declare desc="retrieve port for a specific container"
  local trigger="network-get-port"
  local APP="$1" PROC_TYPE="$2" CONTAINER_INDEX="$3"
  local CONTAINER_PORT=""

  if [[ "web" == "$PROC_TYPE" ]] ; then
      $CONTAINER_PORT="$(config_get "$APP" "DOKKU_WEB_CONTAINER_PORT_$CONTAINER_INDEX")"
  fi

  dokku_log_info1 "Container #$CONTAINER_INDEX is using Port $CONTAINER_PORT"
  echo $CONTAINER_PORT
}

haproxy_configure_post_deploy() {
  declare desc="notify HAPROXY"
  local trigger="post-deploy"
  local APP="$1"

  local HAPROXY_CONFIG_PATH="$DOKKU_ROOT/$APP/HAPROXY_RUNTIME_CONFIG"
  local HAPROXY_CONFIG_CONTENT="$(cat $HAPROXY_CONFIG_PATH)"
  local HAPROXY_ADMIN_URL=$(config_get "$APP" DOKKU_HAPROXY_ADMIN_URL)

  dokku_log_info1 "Updating application routing at $HAPROXY_ADMIN_URL"
  dokku_log_info1 $(curl -q -m 5 "$HAPROXY_ADMIN_URL" -H "Content-Type: application/x-www-form-urlencoded" -d "APP=$APP" -d "CONFIG=$HAPROXY_CONFIG_CONTENT")
}

