#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

haproxy_network_get_port() {
  declare desc="retrieve the port for a specific container after start"
  local trigger="network-get-port"
  local APP="$1" PROC_TYPE="$2" CINDEX="$3" HEROKUISH="$4"
  local TRIGGERTYPE="$(plugn trigger proxy-type "$APP")

  dokku_log_warn "Container $APP $PROC_TYPE $CINDEX $HEROKUISH $TRIGGERTYPE"

  if [[ "$(plugn trigger proxy-type "$APP")" == "haproxy" ]]; then
      haproxy_retrieve_container_port "$APP" "$PROC_TYPE" "$CINDEX" "$HEROKUISH"
  fi
}

haproxy_network_get_port "$@"
