#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

haproxy_network_compute_ports() {
  declare desc="update port map after docker container build"
  local trigger="haproxy_pre_deploy"
  local APP="$1" PROC_TYPE="$2"
}

haproxy_network_compute_ports "$@"
