#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

haproxy_network_write_ipaddr() {
  declare desc="update IP address after docker container start"
  local trigger="haproxy_network_write_ipaddr"
  local APP="$1" PROC_TYPE="$2" CINDEX="$3" IPADDR="$4"

  if [[ "$(plugn trigger proxy-type "$APP")" == "haproxy" ]]; then
      haproxy_configure_container_ipaddr "$APP" "$PROC_TYPE" "$CINDEX" "$IPADDR"
  fi
}

haproxy_network_write_ipaddr "$@"
