#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

haproxy_post_deploy() {
  declare desc="update HAPROXY after all docker containers are started"
  local trigger="haproxy_post_deploy"
  local APP="$1" 

  if [[ "$(plugn trigger proxy-type "$APP")" == "haproxy" ]]; then
      haproxy_configure_post_deploy "$APP"
  else
    # TODO: remove tcp ports from dockerfile
    dokku_log_warn "HAPROXY REMOVE UNIMPLEMENTED"
  fi
}

haproxy_post_deploy "$@"
