#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

haproxy_proxy_build_config() {
  declare desc="rebuild haproxy config to proxy app containers"
  local trigger="haproxy_proxy_build_config"
  local APP="$1" ACTION="$2"

  if [[ "$(get_app_proxy_type "$APP")" == "haproxy" ]]; then
    add_tcp_ports_from_dockerfile "$APP"
  else
    # TODO: remove tcp ports from dockerfile
  fi
}

haproxy_proxy_build_config "$@"
