#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

haproxy_proxy_enable() {
  declare desc="build haproxy config to proxy app containers"
  local trigger="haproxy_proxy_enable"
  local APP="$1" ACTION="$2"

  if [[ "$(plugn trigger proxy-type "$APP")" == "haproxy" ]]; then
    add_tcp_ports_from_dockerfile "$APP"
  fi
}

dokku_log_warn "INFO2----->: $@"

haproxy_proxy_enable "$@"
